# Generated by Django 5.0 on 2025-06-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='referido_por',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_invitacion',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
