# Generated by Django 5.0 on 2025-06-23 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_referido_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_invitacion',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
