# Generated by Django 5.0 on 2025-06-24 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_solicitudretiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitudretiro',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='solicitudretiro',
            name='fecha_aprobacion',
        ),
        migrations.RemoveField(
            model_name='solicitudretiro',
            name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='numero_cuenta',
            field=models.CharField(default='0000000000', max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.banco'),
        ),
    ]
