# Generated by Django 5.0 on 2025-06-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_banco_remove_solicitudretiro_aprobado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudretiro',
            name='banco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.banco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='numero_cuenta',
            field=models.CharField(max_length=50),
        ),
    ]
