# Generated by Django 5.0 on 2025-07-14 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_solicitudretiro_banco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='QR Yape', max_length=100)),
                ('imagen', models.ImageField(upload_to='qr_pagos/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('imagen_voucher', models.ImageField(upload_to='vouchers/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('real', 'Pago Real'), ('falso', 'Pago Falso')], default='pendiente', max_length=10)),
                ('codigo_transferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_rechazo', models.ImageField(blank=True, null=True, upload_to='rechazos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
