# Generated by Django 5.0 on 2025-07-15 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_qrpago_recarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_imagen', models.ImageField(upload_to='qrs/')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecargaFalsa',
            fields=[
            ],
            options={
                'verbose_name': 'Pago Falso',
                'verbose_name_plural': 'Pagos Falsos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.recarga',),
        ),
        migrations.CreateModel(
            name='RecargaPendiente',
            fields=[
            ],
            options={
                'verbose_name': 'Recarga Pendiente',
                'verbose_name_plural': 'Recargas Pendientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.recarga',),
        ),
        migrations.CreateModel(
            name='RecargaReal',
            fields=[
            ],
            options={
                'verbose_name': 'Pago Real',
                'verbose_name_plural': 'Pagos Reales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.recarga',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vip_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NivelCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'nivel')},
            },
        ),
    ]
